export const MESSENGER_NAME = "FACEBOOK";
export const CONFIG_FACEBOOK_API_BASE_URL = "FACEBOOK_API_BASE_URL";
export const CONFIG_FACEBOOK_ACCESS_TOKEN = "FACEBOOK_ACCESS_TOKEN";
export const CONFIG_FACEBOOK_VERIFY_TOKEN = "FACEBOOK_VERIFY_TOKEN";
